#config_version=6

mode:
  start_events: ball_starting
  # stop_events:
  priority: 200

shots:
  jets:
    switch: s_pop_bumper_bottom, s_pop_bumper_right, s_pop_bumper_left

counters:
  lb_jets_count:
    count_events: jets_hit
    starting_count: 0
    count_complete_value: 75
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: lantern_jets_go
  lb_jets_resume:
    enable_events: mode_base_started{current_player.lantern_jets_active>0}
    count_events: jets_hit
    starting_count: 0
    count_complete_value: 25
    count_interval: 1
    direction: up
    persist_state: false
    events_when_complete: lantern_jets_resume_go
    reset_on_complete: true

event_player:
  lantern_jets_go:
    start_mode_lantern_jets
  lantern_jets_go_again:
    start_mode_lantern_jets

variable_player:
  mode_lantern_jets_started:
    lantern_jets_active:
      int: 1
      action: set

show_player:
  mode_lantern_jets_started{current_player.lantern_jets_active>0}:
    lantern_jets_on:
      show_tokens:
        lights: l_lantern_jets




