#config_version=6

mode:
  start_events: start_superman_mode,
  stop_events: stop_mode_superman, start_character_select_superman
  priority: 600

variable_player: 
  # shot_left_ramp_hit:
  #   score: 25000
  # mode_batman_started:
  #   score: 1000000
 
slide_player:
  mode_superman_started: 
    superman_character_select:
      expire: 5s

sound_player:
  slide_superman_character_select_removed: 
    superman_theme:
      action: play
      loops: -1
      bus: music
      volume: 0.05

