#config_version=6

mode:
  start_events: enable_mystery_award
  stop_events: end_mystery_award
  # stop_events:
  priority: 500

ball_holds:
  mystery_scoop:
    balls_to_hold: 1
    hold_devices: bd_mystery_scoop
    enable_events: enable_mystery_award
    disable_events: end_mystery_award, multiball_active
    release_one_events: end_mystery_award

random_event_player:
  ball_hold_mystery_scoop_held_ball:
    events:
      mystery_award_1_event: 30
      mystery_award_2_event: 30
      mystery_award_3_event: 20
      mystery_award_4_event: 10
      mystery_award_5_event: 10
    force_all: true

event_player:
  slide_award_1_slide_removed: end_mystery_award
  slide_award_2_slide_removed: end_mystery_award
  slide_award_3_slide_removed: end_mystery_award
  slide_award_4_slide_removed: end_mystery_award
  slide_award_5_slide_removed: end_mystery_award

slide_player:
  mystery_award_1_event:
    award_1_slide:
      expire: 5s
  mystery_award_2_event:
    award_2_slide:
      expire: 5s
  mystery_award_3_event:
    award_3_slide:
      expire: 5s
  mystery_award_4_event:
    award_4_slide:
      expire: 5s
  mystery_award_5_event:
    award_5_slide:
      expire: 5s

slides:
  award_1_slide:
    - type: text
      text: award_1
      font_size: 100
  award_2_slide:
    - type: text
      text: award_2
      font_size: 100
  award_3_slide:
    - type: text
      text: award_3
      font_size: 100
  award_4_slide:
    - type: text
      text: award_4
      font_size: 100
  award_5_slide:
    - type: text
      text: award_5
      font_size: 100


  

